
package gov.nasa.pds.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Thu Apr 26 23:51:10 EEST 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "DataSetProcessingException", namespace = "http://services.pds.nasa.gov/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSetProcessingException", namespace = "http://services.pds.nasa.gov/", propOrder = {"applicationCode", "creationDate", "errorCode", "information", "message", "moduleCode", "threadName"})

public class DataSetProcessingExceptionBean {

    private java.lang.String applicationCode;
    private java.util.Date creationDate;
    private java.lang.String errorCode;
    private java.lang.Object information;
    private java.lang.String message;
    private java.lang.String moduleCode;
    private java.lang.String threadName;

    public java.lang.String getApplicationCode() {
        return this.applicationCode;
    }

    public void setApplicationCode(java.lang.String newApplicationCode)  {
        this.applicationCode = newApplicationCode;
    }

    public java.util.Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(java.util.Date newCreationDate)  {
        this.creationDate = newCreationDate;
    }

    public java.lang.String getErrorCode() {
        return this.errorCode;
    }

    public void setErrorCode(java.lang.String newErrorCode)  {
        this.errorCode = newErrorCode;
    }

    public java.lang.Object getInformation() {
        return this.information;
    }

    public void setInformation(java.lang.Object newInformation)  {
        this.information = newInformation;
    }

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

    public java.lang.String getModuleCode() {
        return this.moduleCode;
    }

    public void setModuleCode(java.lang.String newModuleCode)  {
        this.moduleCode = newModuleCode;
    }

    public java.lang.String getThreadName() {
        return this.threadName;
    }

    public void setThreadName(java.lang.String newThreadName)  {
        this.threadName = newThreadName;
    }

}

