
package gov.nasa.pds.ws.jaxws;

import gov.nasa.pds.entities.ClassXmlAdapter;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter.DEFAULT;

/**
 * This class was generated by Apache CXF 2.5.2
 * Thu Apr 26 23:51:09 EEST 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "getDataSetRelatedEntitites", namespace = "http://pds.nasa.gov/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDataSetRelatedEntitites", namespace = "http://pds.nasa.gov/", propOrder = {"dataSetId", "relatedEntityType"})

public class GetDataSetRelatedEntitites {

    @XmlElement(name = "dataSetId")
    private long dataSetId;
    @XmlJavaTypeAdapter(value = ClassXmlAdapter.class, type = DEFAULT.class)
    @XmlElement(name = "relatedEntityType")
    private java.lang.Class<?> relatedEntityType;

    public long getDataSetId() {
        return this.dataSetId;
    }

    public void setDataSetId(long newDataSetId)  {
        this.dataSetId = newDataSetId;
    }

    public java.lang.Class<?> getRelatedEntityType() {
        return this.relatedEntityType;
    }

    public void setRelatedEntityType(java.lang.Class<?> newRelatedEntityType)  {
        this.relatedEntityType = newRelatedEntityType;
    }

}

