
package gov.nasa.pds.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Sat May 12 23:39:44 EEST 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "getPreviewImageURL", namespace = "http://pds.nasa.gov/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPreviewImageURL", namespace = "http://pds.nasa.gov/")

public class GetPreviewImageURL {

    @XmlElement(name = "imageFileId")
    private long imageFileId;

    public long getImageFileId() {
        return this.imageFileId;
    }

    public void setImageFileId(long newImageFileId)  {
        this.imageFileId = newImageFileId;
    }

}

