
package gov.nasa.pds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-14T17:08:08.113+03:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "DataSetProcessingException", targetNamespace = "http://pds.nasa.gov/")
public class DataSetProcessingException_Exception extends Exception {
    
    private gov.nasa.pds.DataSetProcessingException dataSetProcessingException;

    public DataSetProcessingException_Exception() {
        super();
    }
    
    public DataSetProcessingException_Exception(String message) {
        super(message);
    }
    
    public DataSetProcessingException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DataSetProcessingException_Exception(String message, gov.nasa.pds.DataSetProcessingException dataSetProcessingException) {
        super(message);
        this.dataSetProcessingException = dataSetProcessingException;
    }

    public DataSetProcessingException_Exception(String message, gov.nasa.pds.DataSetProcessingException dataSetProcessingException, Throwable cause) {
        super(message, cause);
        this.dataSetProcessingException = dataSetProcessingException;
    }

    public gov.nasa.pds.DataSetProcessingException getFaultInfo() {
        return this.dataSetProcessingException;
    }
}
