package gov.nasa.pds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-14T17:08:08.143+03:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://pds.nasa.gov/", name = "PlanetaryDataSystemSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface PlanetaryDataSystemSEI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTargetsInfo", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTargetsInfo")
    @WebMethod
    @ResponseWrapper(localName = "getTargetsInfoResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTargetsInfoResponse")
    public gov.nasa.pds.PagedResults getTargetsInfo(
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page,
        @WebParam(name = "restriction", targetNamespace = "")
        gov.nasa.pds.Restriction restriction
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPreviewImageURL", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetPreviewImageURL")
    @WebMethod
    @ResponseWrapper(localName = "getPreviewImageURLResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetPreviewImageURLResponse")
    public java.lang.String getPreviewImageURL(
        @WebParam(name = "imageFileId", targetNamespace = "")
        long imageFileId
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInstrument", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetInstrument")
    @WebMethod
    @ResponseWrapper(localName = "getInstrumentResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetInstrumentResponse")
    public gov.nasa.pds.Instrument getInstrument(
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchDataSetsByCriteria", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.SearchDataSetsByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "searchDataSetsByCriteriaResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.SearchDataSetsByCriteriaResponse")
    public gov.nasa.pds.PagedResults searchDataSetsByCriteria(
        @WebParam(name = "criteria", targetNamespace = "")
        gov.nasa.pds.SearchCriteria criteria,
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTarget", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTarget")
    @WebMethod
    @ResponseWrapper(localName = "getTargetResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTargetResponse")
    public gov.nasa.pds.Target getTarget(
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTargetTypesInfo", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTargetTypesInfo")
    @WebMethod
    @ResponseWrapper(localName = "getTargetTypesInfoResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTargetTypesInfoResponse")
    public gov.nasa.pds.PagedResults getTargetTypesInfo(
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMission", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetMission")
    @WebMethod
    @ResponseWrapper(localName = "getMissionResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetMissionResponse")
    public gov.nasa.pds.Mission getMission(
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMissionsInfo", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetMissionsInfo")
    @WebMethod
    @ResponseWrapper(localName = "getMissionsInfoResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetMissionsInfoResponse")
    public gov.nasa.pds.PagedResults getMissionsInfo(
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page,
        @WebParam(name = "restriction", targetNamespace = "")
        gov.nasa.pds.Restriction restriction
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDocumentsInfo", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDocumentsInfo")
    @WebMethod
    @ResponseWrapper(localName = "getDocumentsInfoResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDocumentsInfoResponse")
    public gov.nasa.pds.PagedResults getDocumentsInfo(
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page,
        @WebParam(name = "restriction", targetNamespace = "")
        gov.nasa.pds.Restriction restriction
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInstrumentsInfo", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetInstrumentsInfo")
    @WebMethod
    @ResponseWrapper(localName = "getInstrumentsInfoResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetInstrumentsInfoResponse")
    public gov.nasa.pds.PagedResults getInstrumentsInfo(
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page,
        @WebParam(name = "restriction", targetNamespace = "")
        gov.nasa.pds.Restriction restriction
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getImagesInfo", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetImagesInfo")
    @WebMethod
    @ResponseWrapper(localName = "getImagesInfoResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetImagesInfoResponse")
    public gov.nasa.pds.PagedResults getImagesInfo(
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page,
        @WebParam(name = "restriction", targetNamespace = "")
        gov.nasa.pds.Restriction restriction
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDataSetRelatedEntitites", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataSetRelatedEntitites")
    @WebMethod
    @ResponseWrapper(localName = "getDataSetRelatedEntititesResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataSetRelatedEntititesResponse")
    public java.util.List<gov.nasa.pds.EntityInfo> getDataSetRelatedEntitites(
        @WebParam(name = "dataSetId", targetNamespace = "")
        long dataSetId,
        @WebParam(name = "relatedEntityType", targetNamespace = "")
        java.lang.String relatedEntityType
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchEntitiesByType", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.SearchEntitiesByType")
    @WebMethod
    @ResponseWrapper(localName = "searchEntitiesByTypeResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.SearchEntitiesByTypeResponse")
    public gov.nasa.pds.PagedResults searchEntitiesByType(
        @WebParam(name = "entityType", targetNamespace = "")
        java.lang.String entityType,
        @WebParam(name = "searchText", targetNamespace = "")
        java.lang.String searchText,
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page,
        @WebParam(name = "restriction", targetNamespace = "")
        gov.nasa.pds.Restriction restriction
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDataSet", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataSet")
    @WebMethod
    @ResponseWrapper(localName = "getDataSetResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataSetResponse")
    public gov.nasa.pds.DataSet getDataSet(
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDataSetsInfo", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataSetsInfo")
    @WebMethod
    @ResponseWrapper(localName = "getDataSetsInfoResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataSetsInfoResponse")
    public gov.nasa.pds.PagedResults getDataSetsInfo(
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page,
        @WebParam(name = "restriction", targetNamespace = "")
        gov.nasa.pds.Restriction restriction
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDataFile", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataFile")
    @WebMethod
    @ResponseWrapper(localName = "getDataFileResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetDataFileResponse")
    public gov.nasa.pds.WsDataFile getDataFile(
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTargetType", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTargetType")
    @WebMethod
    @ResponseWrapper(localName = "getTargetTypeResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.GetTargetTypeResponse")
    public gov.nasa.pds.TargetType getTargetType(
        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws DataSetProcessingException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchEntities", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.SearchEntities")
    @WebMethod
    @ResponseWrapper(localName = "searchEntitiesResponse", targetNamespace = "http://pds.nasa.gov/", className = "gov.nasa.pds.SearchEntitiesResponse")
    public gov.nasa.pds.SearchResults searchEntities(
        @WebParam(name = "searchText", targetNamespace = "")
        java.lang.String searchText,
        @WebParam(name = "page", targetNamespace = "")
        gov.nasa.pds.Page page
    ) throws DataSetProcessingException_Exception;
}
