package gov.nasa.pds;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-14T17:08:08.153+03:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "PlanetaryDataSystemService", 
                  wsdlLocation = "http://localhost:8080/nasa_pds_ws/services/PlanetaryDataSystemPort?wsdl",
                  targetNamespace = "http://pds.nasa.gov/") 
public class PlanetaryDataSystemService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pds.nasa.gov/", "PlanetaryDataSystemService");
    public final static QName PlanetaryDataSystemPort = new QName("http://pds.nasa.gov/", "PlanetaryDataSystemPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/nasa_pds_ws/services/PlanetaryDataSystemPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlanetaryDataSystemService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/nasa_pds_ws/services/PlanetaryDataSystemPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlanetaryDataSystemService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlanetaryDataSystemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanetaryDataSystemService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PlanetaryDataSystemSEI
     */
    @WebEndpoint(name = "PlanetaryDataSystemPort")
    public PlanetaryDataSystemSEI getPlanetaryDataSystemPort() {
        return super.getPort(PlanetaryDataSystemPort, PlanetaryDataSystemSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlanetaryDataSystemSEI
     */
    @WebEndpoint(name = "PlanetaryDataSystemPort")
    public PlanetaryDataSystemSEI getPlanetaryDataSystemPort(WebServiceFeature... features) {
        return super.getPort(PlanetaryDataSystemPort, PlanetaryDataSystemSEI.class, features);
    }

}
